//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfAppProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class HodowcaPL_Importer
    {
        public int id_produktu { get; set; }
        public Nullable<int> id_hodowcaPL { get; set; }
        public Nullable<int> id_importer { get; set; }
    
        public virtual HodowcaPL HodowcaPL { get; set; }
        public virtual Importer Importer { get; set; }
        public virtual Produkt Produkt { get; set; }
    }
}
