//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfAppProject
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SkelpAkwarystycznyEntities : DbContext
    {
        public SkelpAkwarystycznyEntities()
            : base("name=SkelpAkwarystycznyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<HodowcaPL> HodowcaPLs { get; set; }
        public virtual DbSet<Importer> Importers { get; set; }
        public virtual DbSet<Kategoria> Kategorias { get; set; }
        public virtual DbSet<Klienci> Kliencis { get; set; }
        public virtual DbSet<Produkt> Produkts { get; set; }
        public virtual DbSet<SklepyStacjonarne> SklepyStacjonarnes { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Zamowienia> Zamowienias { get; set; }
        public virtual DbSet<HodowcaPL_Importer> HodowcaPL_Importer { get; set; }
        public virtual DbSet<Zamowienia_Klient> Zamowienia_Klient { get; set; }
        public virtual DbSet<Zamowienia_SklepStacjonarny> Zamowienia_SklepStacjonarny { get; set; }
    }
}
