//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfAppProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produkt
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Produkt()
        {
            this.Zamowienias = new HashSet<Zamowienia>();
        }
    
        public int id_produktu { get; set; }
        public string nazwa_produktu { get; set; }
        public decimal cena_netto { get; set; }
        public decimal cena_brutto { get; set; }
        public int id_kategoria { get; set; }
        public Nullable<int> dostepnych_sztuk { get; set; }
        public Nullable<bool> dostepny { get; set; }
    
        public virtual Kategoria Kategoria { get; set; }
        public virtual HodowcaPL_Importer HodowcaPL_Importer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zamowienia> Zamowienias { get; set; }
    }
}
