//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfAppProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class SklepyStacjonarne
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SklepyStacjonarne()
        {
            this.Zamowienia_SklepStacjonarny = new HashSet<Zamowienia_SklepStacjonarny>();
        }
    
        public int id_sklepu { get; set; }
        public string nazwa_sklepu { get; set; }
        public string telefon { get; set; }
        public string adres_email { get; set; }
        public string adres { get; set; }
        public string kodpocztowy { get; set; }
        public string miejscowość { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zamowienia_SklepStacjonarny> Zamowienia_SklepStacjonarny { get; set; }
    }
}
