//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfAppProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zamowienia_SklepStacjonarny
    {
        public int id_zamowienia { get; set; }
        public System.DateTime data_zlozenia_zamowienia { get; set; }
        public int id_SklepStacjonarny { get; set; }
    
        public virtual SklepyStacjonarne SklepyStacjonarne { get; set; }
        public virtual Zamowienia Zamowienia { get; set; }
    }
}
